# -*- coding: utf-8 -*-
"""lvl_2_task_2.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JB0wyGFTX-qatM3aqHudqf3HbyriIvhX
"""

#пункт А, В
string = "!Hi"
def remove_exclamation_marks(s):
  total_string = ''
  for i in s:
    if i != "!":
       total_string += i
  return  total_string

print(remove_exclamation_marks(string))

#пункт С
string = "Hi !Hi! Hi!"

def remove_word_with_one_em(s):
  word_list = s.split()
  print(word_list)

  Word_total_string = ''

  for word in word_list:
    exclamation_count = 0
    for letter in word:
      if letter == "!":
        exclamation_count += 1
    if exclamation_count != 1:
      Word_total_string += word
      Word_total_string += " "
  return  Word_total_string

remove_word_with_one_em(string)