# -*- coding: utf-8 -*-
"""lvl_2_task_2.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hd_DSaBa2KfezW0EyUlIjAnLY6cCpdjw
"""

list_number = {
                1: "one",
                2: "two",
                3: "three",
                4: "four",
                5: "five",
                6: "six",
                7: "seven",
                8: "eight",
                9: "nine"
              }
number = int(input("Введи число от 0 до 9: "))

def switch_it_up(numb):
  try:
    i = number
    for i in list_number:
      print(list_number[number])
      break
  except KeyError:
    print ("None")
    

switch_it_up(number)