# -*- coding: utf-8 -*-
"""lvl_1 task_1.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wB7ob4AEsT1bkxDdV-6Ye5_j5DDpui6C
"""

my_favorite_songs = 'Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation'

#x = [i for i, ltr in enumerate(my_favorite_songs) if ltr == "t"]
#print(x) 

#y = [i for i, ltr in enumerate(my_favorite_songs) if ltr == "S"]
#print(y)

#z = [i for i, ltr in enumerate(my_favorite_songs) if ltr == "e"]
#print(z)

#for i in enumerate(my_favorite_songs):
  #print(i)

#print(my_favorite_songs.index("S"))

print(my_favorite_songs[0:14])
print(my_favorite_songs[-13:])
print(my_favorite_songs[16:30])
print(my_favorite_songs[-26:-15])

